---
# How do we want it implemented
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
    name: gp2-storage
    annotations:
        storageclass.kubernetes.io/is-default-class: 'true'
provisioner: kubernetes.io/aws-ebs
parameters:
    type: gp2
    fsType: ext4
