# What do want?
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mongo-pvc
spec:
    storageClassName: cloud-ssd
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 3Gi
---
# How do we want it implemented
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: cloud-ssd
provisioner: kubernetes.io/aws-ebs
volumeBindingMode: WaitForFirstConsumer
parameters:
    type: gp2
