# What do want?
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: ebs-mysql-pv-claim
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: ebs-sc
    resources:
        requests:
            storage: 4Gi
---
# How do we want it implemented
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: ebs-sc
provisioner: kubernetes.io/aws-ebs
volumeBindingMode: WaitForFirstConsumer
